export { default as About } from './about'
export { default as Contact } from './contact'
export { default as Portfolio } from './portfolio'
export { default as Thoughts } from './thoughts'
export { default as Nav } from './nav'